name: dag_task_scheduler_builder
description: lib
version: 1.0.0


environment:
  sdk: '>=3.0.0'

dependencies:
  meta: ^1.9.1
  collection: ^1.18.0
  build_config: '>=0.4.4 <2.0.0'
  build: ^2.4.1
  pubspec_parse: ^1.2.3
  source_gen: ^1.4.0
  source_helper: ^1.3.4

dev_dependencies:
  build_runner: ^2.4.6
  build_verify: ^3.1.0
  dart_flutter_team_lints: ^1.0.0
  dart_style: ^2.3.2
  logging: ^1.2.0
  source_gen_test: ^1.0.6
  test: ^1.24.6
  test_descriptor: ^2.0.1
  test_process: ^2.1.0
  yaml: ^3.1.2
